FIZZBUZZ_MSG: .STRING "FizzBuzz
"
FIZZ_MSG: .STRING "Fizz
"
BUZZ_MSG: .STRING "Buzz
"
CUSTOM_MSG_3: .STRING "FizzBuzz\\n"
CUSTOM_MSG_4: .STRING "Fizz\\n"
CUSTOM_MSG_5: .STRING "Buzz\\n"

YOLOAD R1, 1(R0)
LOOP_START_1:
YOLOAD R0, 3(R0)
MODULOIZE R2, R1, R0
SAMEBRO R2, R0, CHECK_SECOND_6
YEET SKIP_FIZZBUZZ_4
CHECK_SECOND_6:
YOLOAD R0, 5(R0)
MODULOIZE R3, R1, R0
SAMEBRO R3, R0, FIZZBUZZ_3
YEET SKIP_FIZZBUZZ_4
FIZZBUZZ_3:
YELLSTR FIZZBUZZ_MSG
YEET END_IF_5
SKIP_FIZZBUZZ_4:
YELLSTR CUSTOM_MSG_3
YELLSTR CUSTOM_MSG_4
YELLSTR CUSTOM_MSG_5
YELLVAL R1
YOLOAD R2, 10(R0)
NOTGREATEROREQUAL R1, R2, LOOP_END_2
INCREMENT R1
YOLO LOOP_START_1
LOOP_END_2:
END_IF_5: