STRING_LITERAL_0: .STRING "UNKNOWN_STRING_0\n"

YOLOAD R1, 1(R0)
YOLOAD R0, 3(R0)
MODULOIZE R2, R1, R0
SAMEBRO R2, R0, LABEL_TARGET_16
YEET LABEL_TARGET_28
YOLOAD R0, 5(R0)
MODULOIZE R3, R1, R0
SAMEBRO R3, R0, LABEL_TARGET_24
LABEL_0:
YEET LABEL_TARGET_28
YELLSTR STRING_LITERAL_0
YEET LABEL_TARGET_44
YELLSTR STRING_LITERAL_0
YELLSTR STRING_LITERAL_0
YELLSTR STRING_LITERAL_0
YELLVAL R1
YOLOAD R2, 10(R0)
LABEL_1:
NOTGREATEROREQUAL R1, R2, LABEL_TARGET_44
INCREMENT R1
YOLO LABEL_0
